Issue #23 - Export Config Policy Enhancement
netascode/terraform-aci-config-export pull request #11
Opened 2023-01-12 16:06 UTC by marehler

Add 'snapshot' parameter to 'fabric policies' - 'config export' as per /netascode/aac issue #23:
https://wwwin-github.cisco.com/netascode/aac/issues/23

2023-01-13 14:12 UTC, danischm requested changes

2023-01-13 14:12 UTC, danischm commented on tests/full/test_full.tf
> +    want        = true
I think the expected value here should be `"yes"`.

2023-01-13 15:14 UTC, marehler commented on tests/full/test_full.tf
> +    want        = true
Right, changed to "yes". Btw, how can you actually execute these tests to identify such issues?

2023-01-24 10:18 UTC, danischm approved these changes

2023-01-24 10:19 UTC, merged